spring:
  application:
    name: example
  profiles:
    active: prod
logging:
  config: classpath:logback-spring.xml
camel:
  springboot:
    name: example
  health.check.routes.enabled: false
management:
  endpoint:
    health:
      show-details: always


